/* Main.c file generated by New Project wizard
 *
 * Created:   jue abr 26 2018
 * Processor: PIC18F45K22
 * Compiler:  MPLAB XC8
 */

#include <xc.h>
#define _XTAL_FREQ 8000000  

#include <string.h>
#include "config.h"
#include "GLCD.h"

// defines varios
#define PINA0 PORTAbits.RA0

// estats
#define INIT 0
#define RUNNING 1
#define STOPPED 2

// Global Variables (decimes, estat del crono, etc.)
unsigned int decimes = 0;
unsigned int segons = 0;
unsigned int minuts = 0;
unsigned int hores = 0;
unsigned char estat = INIT; // initial state
const char * s2 = "hh:mm:ss\n";			// GLCD

void writeTxt(byte page, byte y, char * s) {
	int i=0;
	while (*s!='\n') { 
		putch(page, y+i, *(s++));
		i++;
	};
     }


void interrupt timer(void){ //Interrupt del timer (s'executa cada 100ms)
   if(TMR0IE && TMR0IF){ //Si l'interrupt està donat
      
      //XTAL = 8MHz, volem un T=100ms, 2Mhz = 1/4 fosc,
      //El contador suma cada 0.5us
      //Valor inicial TMR0 = 65535 - (1/32)/0.5*10^-5 + 1 = 59286
      TMR0H = 0xF4;
      TMR0L = 0x24;
      TMR0IF = 0; //Clear del flag
      
      decimes++;
      if (decimes == 10) {
	 decimes = 0;
	 segons++;
	 if(segons == 60){
	    segons = 0;
	    minuts++;
	  } if(minuts == 60){
		  minuts = 0;
		   hores++;
	  }
      }
	
   }
}

void print(void) 
{
	int p = 4;
	
	putch(p,  8, hores / 10 + '0');
	putch(p, 9, hores % 10 + '0');
	
	putch(p, 10, ':');
	
	putch(p, 11, minuts / 10 + '0');
	putch(p, 12, minuts % 10 + '0');
	putch(p, 13, ':');
	putch(p, 14, segons / 10 + '0');	
	putch(p, 15, segons % 10 + '0');
}

void configPIC () {
   
   PORTD=0;
   PORTC=0;
   PORTA = 0;
   PINA0 = 0;
   TRISD = 0x00;
   TRISC = 0x00;	
   TRISA = 0x00;	
   ADCON1=0x0F;		
   INTCON = 0xA0; 	
   RCON = 0;		
   T0CON = 0x94;	// Configuracion Timer0 (Prescaler 1:32)
   TMR0H = 0xF4;	
   TMR0L = 0x24;
}

void tic(){
   print();
   }
   
   int main () {
      
      // GLCD
	configPIC();
	GLCDinit(); // GLCD routines are in rutines_GLCD.C
	clearGLCD(0, 7, 0, 127);
	setStartLine(0);
      
      //TREURE 0
	writeTxt(2,9, s2);
	print();
   
   configPIC();
   while (1) {
      tic();
      if(PINA0){
	 if (estat == 0) { 
	    estat = 1;
	    TMR0ON = 1;
	 }
	 else if (estat == 1) { 
	    estat = 2;
	    TMR0ON = 0;
	 }
	 else if (estat == 2) {
	    estat = 0;
	    decimes = 0;
	    segons = 0;
	 }
      }
      while (PINA0) tic();
   }
}