/* Main.c file generated by New Project wizard
 *
 * Created:   jue abr 26 2018
 * Processor: PIC18F45K22
 * Compiler:  MPLAB XC8
 */

#include <xc.h>
#define _XTAL_FREQ 8000000  

#include <string.h>
#include "config.h"
#include "GLCD.h"

const char * s1 = "Alvaro Moreno Ribot $ \n";
const char* fantasma = "$ \n";

void writeTxt(byte page, byte y, char * s) {
	int i=0;
	while (*s!='\n') { 
		putch(page, y+i, *(s++));
		i++;
	};
}	

void Saluda()
{
	writeTxt(6,1, s1);
}

void Fantasma(){
   writeTxt(6,1,fantasma);
   }
  
void main(void)
 {
	PORTD=0; 		   //Donem uns valors inicials als ports
	PORTB=0;  
        PORTA = 0;
	TRISD = 0x00;		   //Configurem D i B de sortida
	TRISB = 0x00;
         TRISA = 0xFF;
        ANSELA = 0x00; //Digital
    
    
	   GLCDinit();		   //Inicialitzem la pantalla
	    clearGLCD(0,7,0,127);      //Borrem pantalla
	   setStartLine(0);           //Definim inici
    while(1){
        if(PORTAbits.RA0 == 1) {	   
	   if(PORTAbits.RA0 == 0) __delay_ms(200);
	   //Saluda(); // Exercici 2.1
	   Fantasma(); //Exercici 2.2 (Funciona amb els botons igual)
	}
	
	if(PORTAbits.RA1 == 1) clearGLCD(0,7,0,127);  
     }
}
